repos:
  - repo: local
    hooks:
      - id: pytest-backend
        name: Run Backend Tests
        entry: bash -c 'PYTHONPATH=. pytest backend/tests'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: vitest-frontend
        name: Run Frontend Tests
        entry: bash -c 'cd frontend && yarn test'
        language: system
        types: [javascript]
        pass_filenames: false
        always_run: true