name: Frontend Lint (ESLint)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use a recent LTS version

    - name: Install dependencies
      run: yarn install
      working-directory: frontend

    - name: Run ESLint
      run: yarn lint
      working-directory: frontend